name: libre_skill_tree
description: "skill tree of life"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  build_runner: ^2.7.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  graphx: ^1.0.14

  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0

  supabase_flutter: ^2.10.3

dev_dependencies:
  isar_community_generator: ^3.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf

    - family: Oxanium
      fonts:
        - asset: assets/fonts/Oxanium-Regular.ttf
        - asset: assets/fonts/Oxanium-SemiBold.ttf
